--CREATES ep TABLE--
CREATE TABLE ep (ep CHARACTER VARYING(100), get BOOLEAN, post BOOLEAN, put BOOLEAN, delete BOOLEAN, session BOOLEAN, table_name CHARACTER VARYING(100), pkey CHARACTER VARYING(100), get_error CHARACTER VARYING(255), post_error CHARACTER VARYING(255), put_error CHARACTER VARYING(255), delete_error CHARACTER VARYING(255));
